execute:
  freeze: auto

project:
  type: website

website:
  title: "Kilian Sander"
  cookie-consent: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



